name: flutterbloc
description: "export in Flutter Bloc"
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  #Prevent unnecessary rebuilds with Equatable
  equatable: ^2.0.3
#  rxdart: ^0.27.7
  bloc_concurrency: ^0.2.4
  stream_transform: ^2.0.0
  formz: ^0.7.0

  #internal packages
  auth_repo:
    path: packages/auth_repo
  user_repo:
    path: packages/user_repo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
