name: weather_repo
description: "manages the weather domain"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meteo_api:
    path: ../meteo_api

dev_dependencies:
  build_runner: ^2.4.8
  coverage: ^1.0.3
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  test: ^1.16.4
